### ISSUE TITLE
Add event project requirement-contributor request matching process

### ISSUE THREAD

**Issue by jhlegarreta** [brainhackorg/brainmatch#1]
Add event project requirement-contributor request matching process.

Basic assumptions
- Input
  - [bhg2020](https://github.com/brainhackorg/global2020) project issues
  - `BHG2020` event attendee `CSV` files containing attendees' names, email addresses, registered `BHG2020` event/location, skills (background), topics (interests)
- Output: top-5 project matches for each attendee
- Programming language: Python and bash scripts.

A basic procedure can be as follows:
1. Read the [bhg2020](https://github.com/brainhackorg/global2020) project issues' labels using `GitHub` `CLI`s. If labels cannot be read directly, loop over issues, parse the labels and compose a set with them.
1. Read the [bhg2020](https://github.com/brainhackorg/global2020) project issues and build a Pandas dataframe containing all issues marked as being ready.
1. Read the `BHG2020` event attendee `CSV` file into a Pandas dataframe.
1. Loop over attendees. For each attendee:
   1. Loop over the project dataframe and for each project belonging to the event (location) the attendee has registered for, search the project skills/requirements that match with the attendees skills/interests. For each match, add +1 to the score.
  1. Possibly weight differently according to the required skill degree (e.g. +1 for `none`; +2 for `familiar`; +3 for `expert`, etc.)
1. Write the results to a `CSV` file: one row per attendee.
1. Get the top-5 scores for each attendee to notify them (and maybe project leaders?).
   1. Maybe provide two different lists: one corresponding to the skills (background); another one for the topics (interests)

**Comment by eurunuela** [comment]
Thank you @jhlegarreta ! I'd say this is very accurate and helpful. 

My only concern would be point 5. If we weight differently, we will not be able to give a percentage based match. Rather, we'd just mention the top 5 matches.

I'm thinking, shall we open a milestone with deadline on November 2nd? Just to have a better idea of how far we are on the process.

**Comment by eurunuela** [comment]
I just wrote a little BASH script to pull the ID, title and labels of issues on a GitHub repo. You can find it [here](https://github.com/eurunuela/brainmatch/blob/pull_projects/pull_issues.sh).

Once we know what label we will use to filter the accepted projects, [line 4](https://github.com/eurunuela/brainmatch/blob/pull_projects/pull_issues.sh#4) will change slightly so that it only pulls the ID of those issues with the `accepted` label.

Please let me know what you think @jhlegarreta .

**Comment by jhlegarreta** [comment]
> My only concern would be point 5. If we weight differently, we will not be able to give a percentage based match. Rather, we'd just mention the top 5 matches.

My proposal did not have a percentage score, but it looks another way of thinking about it. For now, we can stick to to an unweighted solution (or even weights for all matches), and then see if that solution is satisfying if you wish. It is also easier to begin with.

> I'm thinking, shall we open a milestone with deadline on November 2nd? Just to have a better idea of how far we are on the process.

It is ambitious as date, but go ahead if you wish.

> I just wrote a little BASH script to pull the ID, title and labels of issues on a GitHub repo. You can find it here.

Looks good to me. Thanks.

> Once we know what label we will use to filter the accepted projects, line 4 will change slightly so that it only pulls the ID of those issues with the accepted label.

The label `status:web_ready` has been proposed.

**Comment by anibalsolon** [comment]
Hey @jhlegarreta and @eurunuela ,

Really nice work you all have been doing towards this! Excited to see it working :)

Just to chime in with some views, based on this issue and Jon's PR (sorry I could not follow all the discussions over Mattermost):

> Q1: I assume that projects might not have a large variety of required skills, as we tend to make focused projects instead of wide/big projects. In any case, there might be ties between projects for a person, and if my code skimming was good enough, the first projects of the CSV will be assigned more often given these ties. What if we shuffled the projects rows with a fixed seed for each participant?

> Q2: Following the "favoritism" argument, and given we have the full set of participants & projects*, what if we increase some counter for when a project goes into someone's top-5, so other projects might not be forgotten by accident? Maybe as some sort of weighted randomness for selecting a project for a participant e.g. Proj1 was assigned to 15 ppl, Proj2 was assigned to 5ppl, so the change Proj1 will be assigned for the next participant is 25% (? I guess). And a fixed seed to guarantee some sort of determinism. Maybe it would also be required to shuffle the participants rows, to be fairer.
>  \* new participants/projects would be added to the bottom of the CSV, so maintaining the previous project assignments

> Q3: Jon's point <#7 i> is really interesting. Given it is a BH, in my opinion, interests should be favored. However, people with the skills might be necessary to transfer this knowledge to others. So, following Q2 point, a weighting factor to the randomness would be if the project is saturated with skilled ppl, not giving a chance to those who have an interest in the project.


Of course, my view might overcomplicate things and not be the fairer one (that's why I think including some randomness to the process would benefit it), or you might as well already thought of that. However, happy to hear your take on this!

**Comment by jhlegarreta** [comment]
Thanks for chiming in @anibalsolon. My thoughts on the points raised:

> Q1: I assume that projects might not have a large variety of required skills, as we tend to make focused projects instead of wide/big projects. In any case, there might be ties between projects for a person, and if my code skimming was good enough, the first projects of the CSV will be assigned more often given these ties. What if we shuffled the projects rows with a fixed seed for each participant?

The code at the time the comment was written did not compute the score as it was agreed in this issue; it was using the id/index of the frame just to have a script that was able to complete. And even if the scoring was computed (as it is now), the order is not an issue, right? A project is not scored differently depending on whether it comes before or after another one. The same applies to contributors. The aim was not provide any binding list or to provide a cut-off for project leaders once `M` people are marked as having an affinity to their project. The whole list is generated and the top `N` projects may be listed for each participant (if `N` is set beyond the number of projects, then only a sorting would be made). Thus I assume that the shuffling argument does no longer apply within that context at least (however, your Q2 does suggest that it might be interesting from another point if view).

> Q2: Following the "favoritism" argument, and given we have the full set of participants & projects*, what if we increase some counter for when a project goes into someone's top-5, so other projects might not be forgotten by accident? Maybe as some sort of weighted randomness for selecting a project for a participant e.g. Proj1 was assigned to 15 ppl, Proj2 was assigned to 5ppl, so the change Proj1 will be assigned for the next participant is 25% (? I guess). And a fixed seed to guarantee some sort of determinism. Maybe it would also be required to shuffle the participants rows, to be fairer.
    * new participants/projects would be added to the bottom of the CSV, so maintaining the previous project assignments

It may happen that no matches are found for a given project. OTOH, it would be sad if it happened; OTOH, people attend a BHG to enjoy the event, and it is fair if they do not mention tools or topics they do not want to work on. If fact, I'd say it is desirable. And maybe they attend an event just because they are interested in the talks and not so much in the projects, and they prefer to spend that time doing other things.

Your proposal seems interesting. We did discuss that it would be desirable for project leaders to estimate the appropriate size of a project, but OTOH having a label for integers between `[1,15]` in `GitHub` was judged too much; maybe `{1,3, 5,10,15}` would be a possibility. And in that case, yes, the people to project binding would require some assignment strategy for a project to reach its quota. And yet, filling the quota with the participants considered sequentially as they are read from the data, for the same number of skill matches, might be unfair.

> Q3: Jon's point <#7 i> is really interesting. Given it is a BH, in my opinion, interests should be favored. However, people with the skills might be necessary to transfer this knowledge to others. So, following Q2 point, a weighting factor to the randomness would be if the project is saturated with skilled ppl, not giving a chance to those who have an interest in the project.

I do agree that a contributor's choices or desired topics should be weighted differently than their background from their point of view. A contributor may well decide to attend a BHG because they want to switch gears and learn about new tools, methods, etc. for a number of reasons. And these may well belong to a domain that is not the one they currently work in. A simple solution to this would be to require an additional `JSON` file with weights summing to 100 and propose that the `desired` fields are `weighted` with greater values, and then use those values to weight the matches. 

However, one should also take into account the specificities of a project. From the point of view of a project leader, and depending on the targets of their project for the BHG, a higher level of expertise may be desirable: e.g. a project that is closer to completion or that requires a non-beginner level of expertise so as to hopefully have a part completed within the BHG event. In this case, a level of expertise for a particular subject or tool (beyond the set of tools one is familiar with) might be desirable. Assessing the experience on a tool/skill basis meant complicating things at different levels, starting from the `GitHub` issue labels themselves, so we discarded that.

A general skills level-related label was made available, one for all, although it is very obvious that the skill required for a project may be specific, and a general expertise level is too broad, may not cover such cases or may be misleading. The current method proposal does not use it, because, among others, if that is not asked to participants, then there is little to be done.

Linked to the the `experience` vs. `desire` question, the point about sharing knowledge among participants seems to me very interesting.

All this being said, we opened the issue to have a clear set of tasks so as to have a first working version with a fairly simple solution or baseline, then leave further improvements for subsequent stages.

My take is that:
- There are many, many possibilities and the method can be made more sophisticated, but we may be limited by our personal constraints to address all suggestions.
- The method is not intended to be robust before any situation: we are also limited by the data that registration forms will contain. Furthermore, if the data is not gathered in a given way, the script may well not work as expected: the way we imagined things depends at term on the information gathered in the participant registration form, and we have already seen discrepancies with respect to what we agreed upon or some of the labels might be unused. Hence, unless the form is centralized there is little we can do.
- Sites may or may not use the tool for various reasons.
- The method can be improved as this is an public repository. Some may choose to make local modifications on their own, but the solution provided in the global repository should be as general as possible, a shared vision needs to exist, and the possibilities are exhausting.

The current solution has not been tested extensively either for a few reasons. It has only been tested with the sample data that has been made available.

**Comment by anibalsolon** [comment]
Hey @jhlegarreta Thank you for explaining it to me and going through the points! I understand it better now.

Yes, I agree with your final takes, and I understand it is an on-going project aiming for a deadline. I'd be happy to discuss new iterations then! I am sure this algorithm could be leveraged to other hackathons, Github-based or not 🔥
